version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../instance/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
  client:
    image: hr-management
    volumes:
      - ../client/:/app
    ports:
      - 3000:3000
    networks:
      - webnet
    tty: true
networks:
  webnet:
