import { DataTypes } from 'sequelize'
import sequelize from './db'

const Staff = sequelize.define('Staff', {
  // Model attributes are defined here
  staffId:              { type: DataTypes.INTEGER, field: 'staff_id', allowNull: false, defaultValue: null, },
  photo:                { type: DataTypes.TEXT, defaultValue: null, },
  fullName:             { type: DataTypes.STRING, field: 'full_name', allowNull: false, defaultValue: null, },
  furigana:             { type: DataTypes.STRING, defaultValue: null, },
  maidenName:           { type: DataTypes.STRING, field: 'maiden_name', defaultValue: null, },
  sex:                  { type: DataTypes.STRING, defaultValue: null, },
  bloodType:            { type: DataTypes.STRING, field: 'blood_type', defaultValue: null, },
  birthDate:            { type: DataTypes.DATEONLY, field: 'birth_date', defaultValue: null, },
  joinDate:             { type: DataTypes.DATEONLY, field: 'join_date', defaultValue: null, },
  employedCategory:     { type: DataTypes.STRING, field: 'employed_category', defaultValue: null, },
  location:             { type: DataTypes.STRING, defaultValue: null, },
  projectName:          { type: DataTypes.STRING, field: 'project_name', defaultValue: null, },
  startDate:            { type: DataTypes.DATEONLY, field: 'start_date', defaultValue: null, },
  department:           { type: DataTypes.STRING, defaultValue: null, },
  position:             { type: DataTypes.STRING, defaultValue: null, },
  staffCategory:        { type: DataTypes.STRING, field: 'staff_category', defaultValue: null, },
  isLinkage:            { type: DataTypes.BOOLEAN, field: 'is_linkage', defaultValue: null, },
  staffRank:            { type: DataTypes.STRING, field: 'staff_rank', defaultValue: null, },
  postalCode:           { type: DataTypes.STRING, field: 'postal_code', defaultValue: null, },
  address1:             { type: DataTypes.STRING, defaultValue: null, },
  address2:             { type: DataTypes.STRING, defaultValue: null, },
  address3:             { type: DataTypes.STRING, defaultValue: null, },
  phoneNumber:          { type: DataTypes.STRING, field: 'phone_number', defaultValue: null, },
  mobileNumber:         { type: DataTypes.STRING, field: 'mobile_number', defaultValue: null, },
  isMailing:            { type: DataTypes.BOOLEAN, field: 'is_mailing', defaultValue: null, },
  mailingPostalCode:    { type: DataTypes.STRING, field: 'mailing_postal_code', defaultValue: null, },
  mailingAddress1:      { type: DataTypes.STRING, field: 'mailing_address1', defaultValue: null, },
  mailingAddress2:      { type: DataTypes.STRING, field: 'mailing_address2', defaultValue: null, },
  mailingAddress3:      { type: DataTypes.STRING, field: 'mailing_address3', defaultValue: null, },
  mailingPhoneNumber:   { type: DataTypes.STRING, field: 'mailing_phone_number', defaultValue: null, },
  residencePostalCode:    { type: DataTypes.STRING, field: 'residence_postal_code', defaultValue: null, },
  residenceAddress1:      { type: DataTypes.STRING, field: 'residence_address1', defaultValue: null, },
  residenceAddress2:      { type: DataTypes.STRING, field: 'residence_address2', defaultValue: null, },
  residenceAddress3:      { type: DataTypes.STRING, field: 'residence_address3', defaultValue: null, },
  residencePhoneNumber:   { type: DataTypes.STRING, field: 'residence_phone_number', defaultValue: null, },
  line1:                { type: DataTypes.STRING, defaultValue: null, },
  station1:             { type: DataTypes.STRING, defaultValue: null, },
  line2:                { type: DataTypes.STRING, defaultValue: null, },
  station2:             { type: DataTypes.STRING, defaultValue: null, },
  line3:                { type: DataTypes.STRING, defaultValue: null, },
  station3:             { type: DataTypes.STRING, defaultValue: null, },
  emergencyFullName:    { type: DataTypes.STRING, field: 'emergency_full_name', defaultValue: null, },
  emergencyFurigana:    { type: DataTypes.STRING, field: 'emergency_furigana', defaultValue: null, },
  emergencyRelation:    { type: DataTypes.STRING, field: 'emergency_relation', defaultValue: null, },
  emergencyIsLiveWith:  { type: DataTypes.BOOLEAN, field: 'emergency_is_live_with', defaultValue: null, },
  emergencyPostalCode:  { type: DataTypes.STRING, field: 'emergency_postal_code', defaultValue: null, },
  emergencyAddress1:    { type: DataTypes.STRING, field: 'emergency_address1', defaultValue: null, },
  emergencyAddress2:    { type: DataTypes.STRING, field: 'emergency_address2', defaultValue: null, },
  emergencyAddress3:    { type: DataTypes.STRING, field: 'emergency_address3', defaultValue: null, },
  emergencyPhoneNumber: { type: DataTypes.STRING, field: 'emergency_phone_number', defaultValue: null, },
  remarks:              { type: DataTypes.STRING, defaultValue: null, },
  handicappedCategory:  { type: DataTypes.STRING, field: 'handicapped_category', defaultValue: null, },
  leaveDate:            { type: DataTypes.DATEONLY, field: 'leave_date', defaultValue: null, },
  leaveReason:          { type: DataTypes.STRING, field: 'leave_reason', defaultValue: null, },
  notes:                { type: DataTypes.TEXT, defaultValue: null, },
  createdAt:            { type: DataTypes.DATE, field: 'created_at', defaultValue: null, },
  updatedAt:            { type: DataTypes.DATE, field: 'updated_at', defaultValue: null, },
}, {
  freezeTableName: true
});



export default Staff
